---
title: '#17'
author: "Sajib Devnath"
date: "1/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Library: 

```{r}
pacman::p_load(tidyverse, hrbrthemes, extrafont, geofacet, patchwork, ggrepel)
extrafont::loadfonts(device = 'win',  quiet = TRUE)
theme_set(theme_minimal())
```



Data: 

```{r}
big_mac <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-12-22/big-mac.csv') %>% mutate(year = lubridate::year(date)) 
```


Data Crunching:

```{r}
big_mac %>% 
  mutate(year = lubridate::year(date)) %>% 
  filter(date == min(date)) %>% 
  pull(iso_a3) -> countries
```

```{r}
years <- c(2000, 2005, 2015, 2010, 2020)

big_mac %>% 
  filter(year %in% years, iso_a3 %in% countries) %>% 
  group_by(iso_a3, name, year) %>% 
  summarise(dollar_price = mean(dollar_price)) %>% 
  filter(year %in% c(2000, 2020)) %>%
  mutate(year = as.character(year),
         dollar_price = if_else(year == "2000", dollar_price * 1.51, dollar_price)) %>% 
  arrange(name, year) %>% 
  group_by(name) %>% 
  mutate(change_num = (dollar_price - lead(dollar_price))/dollar_price,
         change_num = if_else(is.na(change_num), 
                              lag(change_num), change_num)) %>% 
  ungroup() %>% 
  mutate(increase = change_num > 0,
         rel_change = case_when(change_num > 0.1 ~ "More than 10% decrease",
                               change_num < -0.1 ~ "More than 10% increase",
                               TRUE ~ "Changes within 10%"),
         rel_change = fct_relevel(rel_change, 
                                 "More than 10% increase",
                                 "Changes within 10%")) -> plot_data


  
```

```{r}
plot_data %>% 
  select(rel_change) %>% 
  filter(rel_change == "Changes within 10%") %>% 
  head(8) %>% 
  rowid_to_column(var = "dollar_price") %>% 
  mutate(dollar_price = dollar_price - 1) -> middle_line
```


Countries for highlighting: 

```{r}
plot_data %>% 
  select(iso_a3, change_num) %>% 
  unique() -> plot_changes
```


```{r}
slice_min(plot_changes, change_num, n = 3) %>% 
  mutate(status = "Three min") %>% 
  bind_rows(slice_min(plot_changes, abs(change_num), n = 3) %>% 
              mutate(status = "Three least")) %>% 
  bind_rows(slice_max(plot_changes, change_num, n = 3) %>% 
              mutate(status = "Three max")) -> plot_change_three 
```


```{r}
plot_data %>% 
  left_join(plot_change_three) %>% 
  mutate(status = if_else(is.na(status), "Regular", status)) -> plot_data2
```


```{r fig.width=12, fig.height=6}
plot_data2 %>%  
  ggplot(aes(x = as.numeric(year), y = dollar_price)) +
  geom_line(data = middle_line, aes(x = 1.5, y = dollar_price), size = 3, color = "grey") +
  geom_point(data = middle_line, aes(x = 1.5, y = dollar_price), size = 3, shape = 21, color = "white", fill = "grey", stroke = 3) +
  geom_label(data = middle_line, aes(x = 1.5, y = dollar_price, label = str_glue("$ {dollar_price}")), label.size = NA, hjust = -.5, color = "grey", fontface = "bold") + 
  geom_text_repel(data = filter(plot_data2, year == "2020"),
                           aes(label = name, color = status),
                           xlim = c(2, NA),
                           direction = "y",
                           force        = 0.5,
                           nudge_x      = 0.05,
                           hjust        = 0,
                           segment.size = 0.1)  +
  geom_text_repel(data = filter(plot_data2, year == "2000"),
                           aes(label = name, color = status),
                           xlim = c(NA, 1),
                           direction = "y",
                           force        = 0.5,
                           nudge_x      = -0.05,
                           hjust        = 1,
                           segment.size = 0.1) +
   geom_line(aes(group = name, color = status)) +
  ggforce::facet_row(~ rel_change) +
  scale_x_discrete(expand = c(0.3, 0.3)) +
  scale_y_continuous(breaks = c(0:7)) +
  scale_color_manual(values = c("#000000bf", "#762a83", "#1b7837", "#1b7837"), 
                     guide = FALSE) +
  theme(
    legend.position = "none"
  ) 
```






























